### ISSUE TITLE
{{@index}} sending no response no value

### ISSUE THREAD

**Issue by steevy1st** [255kb/mockoon#101]
Hi,
As I tried to use the Dummy json, there is a point with {{@index}} giving no value.

i.e: ```
{
          "id" = "{{@index}}"
      }
```
response:
{ "id" = }
or 
```
{
    "id" = {{@index}}
 }
```
response:
Error while parsing JSON during the call

**Comment by 255kb** [comment]
Hi, 
according to their [documentation](https://www.npmjs.com/package/dummy-json) `{{@index}}` can only be used inside a `{{#repeat x}} {{/repeat}}` in order to get the repeat item index. 
If you want to generate some sort of id you can use `{{guid}}` and you will get `"id": "8f5b6e52-67a4-475e-bd4b-d6d43e351a25"`

**Comment by steevy1st** [comment]
thx
