### ISSUE TITLE
Implement route regex

### ISSUE THREAD

**Issue by tmcdos** [255kb/mockoon#55]
I am trying to create a route which will match this regex `/subject/.*` - so that `/subject/abc` and `/subject/123`, etc. are all handled by the same route. However, it seems that the regex is being taken literally - if I try to POST with an URL `http://localhost:3000/subject/.*` I get my response back.
What can I do ?

**Comment by 255kb** [comment]
Hi, 
Mockoon use ExpressJS behind the scene which does support regex syntax. [See here](https://expressjs.com/en/guide/routing.html) under "Route paths".
But in Mockoon I only implemented string-based paths, so as they explain:

> The hyphen (-) and the dot (.) are interpreted literally by string-based paths.

So when declaring a route like this `/.*` ExpressJS will accept:
/.abcd
/.1234
/.* (because * is any character)

If you just want to allow anything you need to only use the `*` so it will accept:
/abcd
/1234

It could still be useful to be able to declare Regex routes in the future so I will rename this ticket so I can track this more easily.

**Comment by tmcdos** [comment]
Thank you for the fast reply!
Indeed, if using only `*` - it solves my use case. I am not sure how useful it will be to support full Regex - perhaps for URL validation, but I think that supporting some sort of `glob` patterns would be sufficient (e.g. `/users/*/assign` or `/manage/*/content/*/add`). Probably `string-based` paths already support such a functionality - I have not tried yet.
Anyway - thank you very much for this handy tool and for your help!

**Comment by 255kb** [comment]
If you have a look at the ExpressJS documentation you will see that it supports most of the regex syntax in string based urls. So yes I am not sure if supporting full regexes will add a lot to the tool. I will keep this issue open in case I have time to work on it. 

Thank you for using Mockoon :)

**Comment by 255kb** [comment]
After investigating more I won't add complete regex support to Mockoon unless requested by more people. I think that Express string based paths are more than enough for now especially if it solved your use case @tmcdos 😃
