### ISSUE TITLE
How to test a post request on mockoon and test it simultaneously?

### ISSUE THREAD

**Issue by aakash1313** [255kb/mockoon#98]
How to response based on certain conditions? 

for example:
if(id == 1) send this response
if(id == 2) send other response?

**Comment by 255kb** [comment]
This is currently not possible. 
Also this feature has already been requested in #75 so I am closing this ticket.

**Comment by aakash1313** [comment]
Thanks for the update. So how do I achieve I want to send a different
response if user id is something. Is there a workaround for this?

Thanks,
Akash

**Comment by 255kb** [comment]
There is no workaround for now, sorry. You will have to declare multiple routes.

**Comment by aakash1313** [comment]
ok :(. That case I will have to change my API calls inside the app
Thanks and Regards,
Akashdeep Singh

**Comment by rostlin** [comment]
Mockoon is really great since you just have to change one line of code on your client. But there should be a good way to test your POST requests as well. If the model takes integers you should be able to set what response you want to get based on a set of values, e.g when posting integers [1,2] you will get a certain response. Keep up the good work! (will definitely spread this around the office)

**Comment by 255kb** [comment]
Hi @rostlin thank you :)
v1.5.0 was released today with #75 
You can now define multiple response for each route, and set basic rules like: if query param X === Y then show response number 1, etc 

I hope it can solve your problem :)
